<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rover_gazebo">

    <gazebo reference="chassis_link">
        <material>Gazebo/DarkGrey</material>
    </gazebo>

<xacro:macro name="rover_wheels_sim" params="left_joint right_joint">
    <joint name="${left_joint}" type="continuous">
        <parent link="base_link"/>
        <child link="diff_wheel_left"/>
        <axis xyz="0 0 1"/>
        <origin xyz="0.0 ${track_distance/2 + track_width/2} ${collision_z_elev}" rpy="-${PI/2} 0 0"/>
    </joint>

    <link name="diff_wheel_left">
        <collision>
            <geometry>
                <cylinder radius="${total_height/2}" length="${track_width}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.1"/>
            <xacro:cylinder_inertia radius="${total_height/2}" length="${track_width}" mass="0.1"/>
        </inertial>
    </link>

    <joint name="${right_joint}" type="continuous">
        <parent link="base_link"/>
        <child link="diff_wheel_right"/>
        <axis xyz="0 0 1"/>
        <origin xyz="0.0 -${track_distance/2 + track_width/2} ${collision_z_elev}" rpy="-${PI/2} 0 0"/>
    </joint>

    <link name="diff_wheel_right">
        <collision>
            <geometry>
                <cylinder radius="${total_height/2}" length="${track_width}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.1"/>
            <xacro:cylinder_inertia radius="${total_height/2}" length="${track_width}" mass="0.1"/>
        </inertial>
    </link>
</xacro:macro>

<xacro:macro name="camera_gazebo" params="camera_base_frame camera_topic camera_info_topic">
    <xacro:include filename="$(find realsense2_description)/urdf/_d435i.urdf.xacro"/>

    <xacro:sensor_d435i parent="${camera_base_frame}" use_nominal_extrinsics="true">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:sensor_d435i>


    <joint name="rover_camera_joint" type="fixed">
        <origin xyz="${chassis_length/2 - 0.02} 0.0 ${chassis_height - 0.01}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="${camera_base_frame}"/>
    </joint>

    <link name="${camera_base_frame}">        
    </link>    

    <!-- IMU Integration --> 

    <gazebo reference="camera_depth_frame">
        <sensor name="${camera_base_frame}" type="depth">
            <update_rate>20</update_rate>
            <camera>
            <horizontal_fov>1.047198</horizontal_fov>
            <image>
                <width>640</width>
                <height>480</height>
                <format>R8G8B8</format>
            </image>
            <clip>
                <near>0.05</near>
                <far>3</far>
            </clip>
            </camera>
            <plugin name="${camera_base_frame}_controller" filename="libgazebo_ros_openni_kinect.so">
            <baseline>0.2</baseline>
            <alwaysOn>true</alwaysOn>
            <updateRate>1.0</updateRate>
            <cameraName>rover</cameraName>
            <imageTopicName>${camera_topic}</imageTopicName>
            <cameraInfoTopicName>${camera_info_topic}</cameraInfoTopicName>
            <depthImageTopicName>depth/${camera_topic}</depthImageTopicName>
            <depthImageInfoTopicName>depth/${camera_info_topic}</depthImageInfoTopicName>
            <pointCloudTopicName>depth/points</pointCloudTopicName>
            <frameName>camera_depth_optical_frame</frameName>
            <pointCloudCutoff>0.5</pointCloudCutoff>
            <pointCloudCutoffMax>3.0</pointCloudCutoffMax>
            <distortionK1>0.00000001</distortionK1>
            <distortionK2>0.00000001</distortionK2>
            <distortionK3>0.00000001</distortionK3>
            <distortionT1>0.00000001</distortionT1>
            <distortionT2>0.00000001</distortionT2>
            <CxPrime>0</CxPrime>
            <Cx>0</Cx>
            <Cy>0</Cy>
            <focalLength>0</focalLength>
            <hackBaseline>0</hackBaseline>
            </plugin>
        </sensor>
    </gazebo>
</xacro:macro>


<xacro:macro name="lidar_gazebo_sensor" params="laser_frame laser_topic" > 
    <joint name="lidar_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="${laser_frame}"/>
        <!-- the lidar has been raised by 5mm with respect to its original position because of laser rays detecting ghost shapes -->
        <origin xyz="0.0 0.0 ${0.22+0.005}" rpy="0.0 0.0 0 "/> <!-- rpy had a 180 deg rotation on y and 0 on z -->
    </joint>


    <link name="${laser_frame}">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.001"/>
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        </inertial>
    </link>
    
    <gazebo reference="${laser_frame}">
      <sensor type="ray" name="head_hokuyo_sensor">
        <pose>0 0 0 0 0 0 </pose> <!-- rpy: y was -{PI} rotation on y and 0 on z-->
        <visualize>true</visualize>
        <update_rate>40</update_rate>
        <ray>
            <scan>
              <horizontal>
                <samples>720</samples>
                <resolution>1</resolution>
                <min_angle>-${PI} </min_angle>
                <max_angle>${PI} </max_angle>
              </horizontal>
            </scan>
            <range>
              <min>0.01</min>
              <max>20.0</max>
              <resolution>0.01</resolution>
            </range>
            <noise>
              <type>gaussian</type>
              <!-- Noise parameters based on published spec for Hokuyo laser
                    achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
                    stddev of 0.01m will put 99.7% of samples within 0.03m of the true
                    reading. -->
              <mean>0.0</mean>
              <stddev>0.01</stddev>
            </noise>
        </ray>
        <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
            <topicName>${laser_topic}</topicName>
            <frameName>${laser_frame}</frameName>
        </plugin>
      </sensor>
    </gazebo>

</xacro:macro>

<xacro:macro name="gazebo_diff_drive_controller" params="left_joint right_joint">
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <legacyMode>true</legacyMode>
            <rosDebugLevel>Debug</rosDebugLevel>
            <publishWheelTF>false</publishWheelTF>
            <robotNamespace>/</robotNamespace>
            <publishTf>1</publishTf>
            <publishWheelJointState>false</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <leftJoint>${left_joint}</leftJoint>
            <rightJoint>${right_joint}</rightJoint>
            <wheelSeparation>${total_width - track_width}</wheelSeparation>
            <wheelDiameter>${total_height}</wheelDiameter>
            <broadcastTF>1</broadcastTF>
            <wheelTorque>30</wheelTorque>
            <wheelAcceleration>1.8</wheelAcceleration>
            <commandTopic>cmd_vel</commandTopic>
            <odometryFrame>odom</odometryFrame>
            <odometryTopic>odom</odometryTopic>
            <odometrySource>0</odometrySource>
            <!-- 0=ENCODER, 1=WORLD -->
            <robotBaseFrame>base_footprint</robotBaseFrame>
        </plugin>
    </gazebo>
</xacro:macro>

<xacro:macro name="gazebo_wheel_contact">
    <gazebo reference="diff_wheel_left">
        <mu1 value="1.0"/>
        <mu2 value="1.0"/>
        <kp value="1e15"/>
        <kd value="1e13"/>
        <fdir1 value="0 0 1"/>
    </gazebo>

    <gazebo reference="diff_wheel_right">
        <mu1 value="1.0"/>
        <mu2 value="1.0"/>
        <kp value="1e15"/>
        <kd value="1e13"/>
        <fdir1 value="0 0 1"/>
    </gazebo>

    <gazebo reference="collision_f_l">
        <mu1 value="0.1"/>
        <mu2 value="0.1"/>
        <kp value="10000000.0"/>
        <kd value="100.0"/>
        <minDepth>0.001</minDepth>
    </gazebo>

    <gazebo reference="collision_f_r">
        <mu1 value="0.1"/>
        <mu2 value="0.1"/>
        <kp value="10000000.0"/>
        <kd value="100.0"/>
        <minDepth>0.001</minDepth>
    </gazebo>

    <gazebo reference="collision_b_l">
        <mu1 value="0.1"/>
        <mu2 value="0.1"/>
        <kp value="10000000.0"/>
        <kd value="100.0"/>
        <minDepth>0.001</minDepth>
    </gazebo>

    <gazebo reference="collision_b_r">
        <mu1 value="0.1"/>
        <mu2 value="0.1"/>
        <kp value="10000000.0"/>
        <kd value="100.0"/>
        <minDepth>0.001</minDepth>
    </gazebo>
</xacro:macro>

    
</robot>